### ISSUE TITLE
Can this be installed on Google CloudSQL?

### ISSUE THREAD

**Issue by bryanconlon** [cybertec-postgresql/pg_permissions#6]
Was wondering is this could be installed on Google CloudSQL?

**Comment by laurenz** [comment]
I doubt it. You'd have to lobby at Google to get the software installed on their machines, and I wouldn't hold my breath while I'm waiting for it to happen.

**Comment by laurenz** [comment]
But actually, you don't really need to create the extension to use it. Since it is plain SQL and PL/pgSQL code, you could simply remove the first line from `pg_permissions--1.2.sql` and run the script. It will create all the database objects. If you want it in a different schema, set the `search_path` appropriately.

**Comment by kovmir** [comment]
No, it could not.

From https://cloud.google.com/sql/docs/postgres/extensions#using-postgresql-extensions:
> You can install only the extensions that are supported by Cloud SQL. For more information, see [PostgreSQL extensions supported by Cloud SQL](https://cloud.google.com/sql/docs/postgres/extensions#postgresql-extensions-supported-by-cloud-sql).
